--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";
create extension if not exists "pgcrypto" with schema "extensions";
create extension if not exists "btree_gist" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.clinics (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    slug text not null unique,
    phone text,
    email text,
    address jsonb,
    timezone text not null default 'Europe/Bratislava',
    language text not null default 'sk',
    subscription_tier text not null default 'tier1',
    subscription_status text not null default 'trial',
    config jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.clinic_members (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null,
    clinic_id uuid not null,
    role text not null check (role in ('owner', 'receptionist', 'dentist', 'super_admin')),
    full_name text,
    created_at timestamp with time zone not null default now(),
    unique (user_id, clinic_id)
);

create table public.patients (
    id uuid primary key default gen_random_uuid(),
    clinic_id uuid not null,
    first_name text not null,
    last_name text not null,
    phone text not null,
    email text,
    date_of_birth date,
    language text not null default 'sk',
    notes text,
    tags jsonb not null default '[]'::jsonb,
    last_visit_at timestamp with time zone,
    do_not_contact boolean not null default false,
    do_not_contact_reason text,
    consent_given_at timestamp with time zone,
    consent_source text,
    data_retention_until timestamp with time zone,
    source text not null default 'manual',
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    created_by uuid
);

create table public.services (
    id uuid primary key default gen_random_uuid(),
    clinic_id uuid not null,
    name text not null,
    duration_minutes integer not null,
    buffer_minutes integer not null default 0,
    color text not null default '#3B82F6',
    description text,
    active boolean not null default true,
    display_order integer not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.clinic_closures (
    id uuid primary key default gen_random_uuid(),
    clinic_id uuid not null,
    date date not null,
    reason text,
    created_at timestamp with time zone not null default now(),
    unique (clinic_id, date)
);

create table public.appointments (
    id uuid primary key default gen_random_uuid(),
    clinic_id uuid not null,
    patient_id uuid not null,
    service_id uuid not null,
    starts_at timestamp with time zone not null,
    ends_at timestamp with time zone not null,
    status text not null default 'scheduled' check (status in ('scheduled', 'reminder_sent', 'confirmed', 'cancelled', 'needs_reschedule', 'completed', 'no_show')),
    source text not null default 'manual' check (source in ('manual', 'ai_voice', 'ai_sms', 'imported')),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    created_by uuid,
    confirmed_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    cancel_reason text,
    notes text,
    patient_notes text
);

create table public.chairside_activity_log (
    id uuid primary key default gen_random_uuid(),
    clinic_id uuid not null,
    actor_type text not null check (actor_type in ('user', 'ai', 'system', 'patient')),
    actor_id uuid,
    actor_label text,
    action text not null,
    entity_type text,
    entity_id uuid,
    details jsonb,
    created_at timestamp with time zone not null default now()
);

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.clinic_members
    add constraint clinic_members_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade;

alter table public.clinic_members
    add constraint clinic_members_clinic_id_fkey foreign key (clinic_id) references public.clinics(id) on delete cascade;

alter table public.patients
    add constraint patients_clinic_id_fkey foreign key (clinic_id) references public.clinics(id) on delete cascade;

alter table public.patients
    add constraint patients_created_by_fkey foreign key (created_by) references auth.users(id);

alter table public.services
    add constraint services_clinic_id_fkey foreign key (clinic_id) references public.clinics(id) on delete cascade;

alter table public.clinic_closures
    add constraint clinic_closures_clinic_id_fkey foreign key (clinic_id) references public.clinics(id) on delete cascade;

alter table public.appointments
    add constraint appointments_clinic_id_fkey foreign key (clinic_id) references public.clinics(id) on delete cascade;

alter table public.appointments
    add constraint appointments_patient_id_fkey foreign key (patient_id) references public.patients(id) on delete cascade;

alter table public.appointments
    add constraint appointments_service_id_fkey foreign key (service_id) references public.services(id);

alter table public.appointments
    add constraint appointments_created_by_fkey foreign key (created_by) references auth.users(id);

alter table public.appointments
    add constraint appointments_no_overlap exclude using gist (
        clinic_id with =,
        tstzrange(starts_at, ends_at) with &&
    ) where (status not in ('cancelled', 'no_show'));

alter table public.chairside_activity_log
    add constraint chairside_activity_log_clinic_id_fkey foreign key (clinic_id) references public.clinics(id) on delete cascade;

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index clinic_members_user_id_idx on public.clinic_members using btree (user_id);
create index clinic_members_clinic_id_idx on public.clinic_members using btree (clinic_id);
create index patients_clinic_id_idx on public.patients using btree (clinic_id);
create unique index patients_clinic_phone_idx on public.patients using btree (clinic_id, phone);
create index patients_clinic_last_visit_at_idx on public.patients using btree (clinic_id, last_visit_at);
create index services_clinic_id_idx on public.services using btree (clinic_id);
create index clinic_closures_clinic_id_idx on public.clinic_closures using btree (clinic_id);
create index appointments_clinic_starts_at_idx on public.appointments using btree (clinic_id, starts_at);
create index appointments_patient_id_idx on public.appointments using btree (patient_id);
create index appointments_clinic_status_starts_at_idx on public.appointments using btree (clinic_id, status, starts_at);
create index chairside_activity_log_clinic_created_at_idx on public.chairside_activity_log using btree (clinic_id, created_at desc);
create index chairside_activity_log_entity_idx on public.chairside_activity_log using btree (entity_type, entity_id);
create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);
